### ISSUE TITLE
Feature: Correct Bad File Type

### ISSUE THREAD

**Issue by zeroasterisk** [zeroasterisk/optim#1]
Mike has a few images which are bad file types, named as jpgs but actually some other type of image... 

Can we find any imagemin plugin (or other tool) which can resolve those images to the correct type?

Maybe something based on this?
https://en.wikipedia.org/wiki/List_of_file_signatures

**Comment by michaeldistler** [comment]
Turns out the files were actually '.webp' files. I was able to fix the file(s) with a small python script. I'll link to it once I get these deploys fixed.

**Comment by zeroasterisk** [comment]
We could pass through this (or something like it) --- maybe before imagemin:
https://github.com/sindresorhus/file-type

If the mime type comes back, change on update
If the ext comes back, change on update
For either changes, put the orig values into `Metadata`

see #4 for additional (unrelated) feature which would trigger a postback

**Comment by michaeldistler** [comment]
This is currently being used in deploy:
https://github.com/eltorocorp/cc2_common/blob/45840f0f120d745b681bebfabe575dffd23321e4/change_file_ext.py
